name: ESLint Check for Pull Requests

on: [ pull_request ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Client depedencies
        working-directory: ./client
        run: npm install

      - name: Run ESLint on Client
        working-directory: ./client
        run: npm run lint

      - name: Install Server depedencies
        working-directory: ./server
        run: npm install

      - name: Run ESLint on Server
        working-directory: ./client
        run: npm run lint
